// Generated by gen_gs.py: the gather/scatter modes (ids 400+) and their tables, shared by kernel and host.
// Compiled only with ENERCAT_GS (build/enercat_gs). Do not edit; re-run gen_gs.py.
#pragma once
#include <stdint.h>
#define EC_GS_FIRST 400
#define EC_GS_COUNT 34
#define EC_GS_MAGIC 0x47530000u
#define EC_GS_SEED 4720260925ull
#define GS_F_GATHER 1
#define GS_F_SCATTER 2
#define GS_F_G32 3
#define GS_F_S32 4
#define GS_F_UPD 5
#define GS_F_FAMO 6
#define GS_F_BLD 7
#define GS_F_BST 8
#define GS_F_AMO 9
#define GS_F_PROBE 10
#define GS_FORM_L1 0
#define GS_FORM_LOCAL 1
#define GS_FORM_GLOBAL 2
#define GS_SHARE_HART 0
#define GS_SHARE_SHIRE 1
#define GS_SHARE_CHIP 2
#define GS_SCP_BYTES 16384u       // scratchpad table per hart (the upper 16 KB of the minion's 32 KB is hart 1's)
#define GS_SCP_OFF (256u * 1024u)  // scratchpad tables start here (offset 0 of a shire's scratchpad faults)
#define GS_CHECK_MIN 512u          // check bytes per participant at least (probe); gathers: 256 per verify visit
#define GS_SENTINEL 0x5A5AC3C3u    // masked-off gather lanes keep this (the verify launches check it)
// FP registers: only caller-saved ones (f0-f7 index vectors, f10-f17 sinks/data/addends, f28-f31), so the compiler
// never saves/restores an FP register inside the gs code (a restore then save is itself a VPURF hazard)
#define GS_SHIRE_TABLE (256u * 1024u)
#define GS_CHIP_TABLE (8u * 1024u * 1024u)
// Params buffer (host -> kernel, one per launch): int32 idx[8][8] at 0, uint64 fields[8] at 256.
#define GS_PARAM_IDX 0
#define GS_PARAM_F32 256
#define GS_PARAM_BYTES 512
#define EC_GS_SCALAR_LO 427   // the scalar baselines (flw, fsw, amoadd*.w): base + 2048 + imm
#define EC_GS_SCALAR_HI 432
#define GS_PROBE_FW 0x53977ull   // probe fg32w/fsc32w fields: lane e -> word [7, 6, 5, 4, 3, 2, 1, 0]
#define GS_PROBE_FH 0xa10369cfull   // probe fg32h fields: lane e -> halfword [15, 12, 9, 6, 3, 0, 1, 10]
#define GS_PROBE_FB 0x184cb8575full   // probe fg32b/fsc32b fields: lane e -> byte [31, 26, 21, 16, 11, 6, 1, 3]
#ifdef __cplusplus
struct EcGsOp { const char* name; unsigned mode; int family; int form; int elem; unsigned btile; const char* unit; const char* note; };
static const EcGsOp EC_GS_OPS[] = {
  {"fgw.ps", 400, 1, 0, 4, 0, "element", "gather through the L1"},
  {"fgh.ps", 401, 1, 0, 2, 0, "element", "gather through the L1"},
  {"fgb.ps", 402, 1, 0, 1, 0, "element", "gather through the L1"},
  {"fgwl.ps", 403, 1, 1, 4, 0, "element", "gather bypassing the L1, to the shire's L2"},
  {"fghl.ps", 404, 1, 1, 2, 0, "element", "gather bypassing the L1, to the shire's L2"},
  {"fgbl.ps", 405, 1, 1, 1, 0, "element", "gather bypassing the L1, to the shire's L2"},
  {"fgwg.ps", 406, 1, 2, 4, 0, "element", "gather bypassing L1 and L2, to the home (L3 slice, scratchpad or memory)"},
  {"fghg.ps", 407, 1, 2, 2, 0, "element", "gather bypassing L1 and L2, to the home (L3 slice, scratchpad or memory)"},
  {"fgbg.ps", 408, 1, 2, 1, 0, "element", "gather bypassing L1 and L2, to the home (L3 slice, scratchpad or memory)"},
  {"fscw.ps", 409, 2, 0, 4, 0, "element", "scatter through the L1"},
  {"fsch.ps", 410, 2, 0, 2, 0, "element", "scatter through the L1"},
  {"fscb.ps", 411, 2, 0, 1, 0, "element", "scatter through the L1"},
  {"fscwl.ps", 412, 2, 1, 4, 0, "element", "scatter bypassing the L1, to the shire's L2"},
  {"fschl.ps", 413, 2, 1, 2, 0, "element", "scatter bypassing the L1, to the shire's L2"},
  {"fscbl.ps", 414, 2, 1, 1, 0, "element", "scatter bypassing the L1, to the shire's L2"},
  {"fscwg.ps", 415, 2, 2, 4, 0, "element", "scatter bypassing L1 and L2, to the home"},
  {"fschg.ps", 416, 2, 2, 2, 0, "element", "scatter bypassing L1 and L2, to the home"},
  {"fscbg.ps", 417, 2, 2, 1, 0, "element", "scatter bypassing L1 and L2, to the home"},
  {"fg32w.ps", 418, 3, 0, 4, 0, "element", "restricted gather: one 32 B block, lanes permuted by packed fields"},
  {"fg32h.ps", 419, 3, 0, 2, 0, "element", "restricted gather: one 32 B block, lanes permuted by packed fields"},
  {"fg32b.ps", 420, 3, 0, 1, 0, "element", "restricted gather: one 32 B block, lanes permuted by packed fields"},
  {"fsc32w.ps", 421, 4, 0, 4, 0, "element", "restricted scatter: one 32 B block"},
  {"fsc32h.ps", 422, 4, 0, 2, 0, "element", "restricted scatter: one 32 B block"},
  {"fsc32b.ps", 423, 4, 0, 1, 0, "element", "restricted scatter: one 32 B block"},
  {"upd", 424, 5, 0, 4, 0, "update", "gather + fadd.ps 1.0 + scatter on the same indices: software scatter-add"},
  {"famoaddl.pi", 425, 6, 1, 4, 0, "update", "packed atomic add, local (shire L2)"},
  {"famoaddg.pi", 426, 6, 2, 4, 0, "update", "packed atomic add, global (home L3)"},
  {"flw.t4096", 427, 7, 0, 4, 4096, "element", "scalar flw, the rand offsets as immediates: the scalar-indexed baseline"},
  {"flw.t512", 428, 7, 0, 4, 512, "element", "scalar flw, the rand offsets as immediates: the scalar-indexed baseline"},
  {"fsw.t4096", 429, 8, 0, 4, 4096, "element", "scalar fsw, the rand offsets as immediates"},
  {"fsw.t512", 430, 8, 0, 4, 512, "element", "scalar fsw, the rand offsets as immediates"},
  {"amoaddl.w.t4096", 431, 9, 1, 4, 4096, "update", "scalar local atomic add per update (addi + amo)"},
  {"amoaddg.w.t4096", 432, 9, 2, 4, 4096, "update", "scalar global atomic add per update (addi + amo)"},
  {"probe", 433, 10, 0, 4, 0, "probe", "the semantic probes of the design (sign extension, fg32 fields, masks, lane conflicts, famo old values, gsc_progress)"},
};
static const char* const EC_GS_PATTERNS[7] = {"unit", "s2", "s4", "s16", "line", "rand", "bcast"};
static const unsigned EC_GS_PAT_TILE[7] = {256, 512, 1024, 4096, 512, 4096, 512};
static const double EC_GS_PAT_LINES[7] = {0.5, 1, 2, 8, 1, 8, 1};
static const int32_t EC_GS_IDX[7][64] = {
  {0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200, 204, 208, 212, 216, 220, 224, 228, 232, 236, 240, 244, 248, 252},
  {0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496, 504},
  {0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008},
  {28, 96, 180, 248, 268, 364, 388, 480, 528, 580, 700, 736, 812, 848, 920, 988, 1048, 1116, 1192, 1220, 1320, 1404, 1424, 1484, 1596, 1644, 1684, 1768, 1840, 1856, 1964, 2024, 2096, 2112, 2196, 2264, 2332, 2368, 2460, 2528, 2612, 2624, 2716, 2812, 2844, 2908, 2952, 3012, 3108, 3152, 3220, 3312, 3336, 3436, 3500, 3556, 3600, 3664, 3728, 3800, 3896, 3916, 4008, 4064},
  {52, 60, 36, 44, 56, 32, 12, 20, 108, 124, 72, 104, 68, 92, 84, 64, 128, 136, 152, 168, 156, 144, 140, 176, 248, 196, 224, 204, 252, 192, 208, 212, 316, 280, 300, 284, 288, 292, 256, 304, 368, 324, 360, 376, 332, 344, 320, 336, 444, 412, 392, 400, 428, 424, 436, 396, 460, 472, 504, 480, 492, 464, 452, 488},
  {1744, 2880, 2152, 952, 1628, 1804, 264, 1996, 72, 2660, 2812, 824, 1028, 3952, 2072, 3052, 708, 3756, 3180, 576, 1904, 3564, 3076, 2720, 4048, 1128, 3200, 3284, 1952, 1328, 2340, 3668, 224, 892, 1364, 1540, 1700, 424, 512, 2524, 3404, 696, 2564, 3592, 3840, 172, 2848, 12, 2476, 1244, 3368, 456, 3808, 1468, 3468, 1012, 2224, 2964, 4020, 336, 2408, 1184, 2288, 1516},
  {28, 28, 28, 28, 28, 28, 28, 28, 84, 84, 84, 84, 84, 84, 84, 84, 180, 180, 180, 180, 180, 180, 180, 180, 204, 204, 204, 204, 204, 204, 204, 204, 300, 300, 300, 300, 300, 300, 300, 300, 340, 340, 340, 340, 340, 340, 340, 340, 400, 400, 400, 400, 400, 400, 400, 400, 480, 480, 480, 480, 480, 480, 480, 480},
};
// restricted forms, per element size w/h/b: per instruction b the lane -> slot map and the packed field word
static const int EC_GS_F32_BITS[3] = {3, 4, 5};
static const int EC_GS_F32_PERM[3][8][8] = {
  {{6, 5, 1, 3, 0, 7, 2, 4}, {6, 5, 7, 1, 2, 4, 0, 3}, {1, 3, 0, 6, 2, 5, 7, 4}, {5, 4, 2, 3, 7, 6, 0, 1}, {4, 6, 7, 1, 5, 3, 2, 0}, {7, 6, 0, 1, 3, 2, 5, 4}, {7, 4, 1, 3, 6, 5, 2, 0}, {1, 7, 6, 4, 0, 2, 3, 5}},
  {{14, 15, 11, 7, 5, 2, 13, 8}, {5, 13, 4, 8, 9, 14, 6, 7}, {10, 4, 3, 9, 6, 2, 1, 13}, {2, 0, 8, 5, 14, 3, 10, 1}, {13, 10, 12, 0, 14, 11, 3, 5}, {8, 3, 11, 12, 10, 6, 15, 9}, {2, 13, 10, 5, 6, 12, 1, 8}, {7, 9, 5, 6, 10, 8, 13, 0}},
  {{21, 9, 19, 16, 1, 31, 5, 30}, {4, 1, 9, 29, 27, 17, 15, 25}, {28, 23, 30, 14, 4, 26, 3, 20}, {7, 5, 31, 15, 17, 0, 18, 21}, {29, 31, 8, 24, 16, 6, 7, 19}, {12, 11, 29, 31, 7, 6, 16, 15}, {11, 20, 22, 30, 29, 23, 10, 0}, {2, 15, 7, 31, 3, 20, 19, 25}},
};
static const uint64_t EC_GS_F32_WORD[3][8] = {
  {0x8b866eull, 0x6223eeull, 0x9eac19ull, 0x2376a5ull, 0x9d3f4ull, 0x953237ull, 0xae667ull, 0xad09b9ull},
  {0x8d257bfeull, 0x76e984d5ull, 0xd126934aull, 0x1a3e5802ull, 0x53be0cadull, 0x9f6acb38ull, 0x81c65ad2ull, 0xd8a6597ull},
  {0xf17e184d35ull, 0xcbe3bea424ull, 0xa0f4477afcull, 0xac8117fca7ull, 0x99cd0c23fdull, 0x7c0c7ff56cull, 0x2afdf5a8bull, 0xcce83f9de2ull},
};
#endif
